# -*- coding: utf-8 -*-
"""Uber project solved.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lpYMvmqNzomtOnOop8J7290XiSBG5LxE

### Uber Pickups Analysis Quiz

The question set is based on the August dataset, `uber-raw-data-aug14.csv`.

#### Keeping the dataset ready before questions
"""

import pandas as pd

df = pd.read_csv('/content/uber-raw-data-aug14.csv')
df.head()

df.info()

"""#### Q1. On what date did we see the most number of Uber pickups?

**Skill Test:** Grouping & Counting
"""

# Convert the 'Date/Time' column to datetime format
#df['Date/Time'] = pd.to_datetime(df['Date/Time'])
print(type(df.loc[0,'Date/Time']))

# Group by date and count the number of pickups

pickupsCountByDate = df.groupby(df['Date/Time'].dt.date).size()
pickupsCountByDate.head()
# Find the date with the highest number of pickups

pickupsCountByDate.idxmax()

"""#### Q.2 How many Uber pickups were made on the date with the highest number of pickups?

**Skill Test:** Indexing and filtering
"""

# Filter the DataFrame to include only the rows for the date with the highest number of pickups
print("The count of pickups on the highest date are", pickupsCountByDate.max())


# Get the count of pickups on the highest date

"""#### Q.3 How many unique TLC base companies are affiliated with the Uber pickups in the dataset?

**Skill Test:** Counting unique values
"""

# Count the number of unique TLC base companies
uniqueBaseCount = df.groupby('Base').size()

"""#### Q.4 Which TLC base company had the highest number of pickups?

**Skill Test:** Grouping, counting, and finding the maximum
"""

# Group by TLC base company and count the number of pickups


# Find the TLC base company with the highest number of pickups
print(uniqueBaseCount.idxmax())

"""#### Q.5 How many Uber pickups were made at each unique TLC base company?

**Skill Test:** Grouping and counting
"""

# Group by TLC base company and count the number of pickups
uniqueBaseCount = df.groupby('Base').size()
print(uniqueBaseCount)

"""#### Q.6 Can you determine the busiest time of day for Uber pickups based on the date/time column?

**Skill Test:** Extracting time components, grouping, counting, and finding the maximum
"""

# Extract the hour from the 'Date/Time' column
df['Hour'] = df['Date/Time'].dt.hour


# Group by hour and count the number of pickups

hourlyPickups = df.groupby('Hour').size()

# Find the hour with the highest number of pickups

print("Busiest time of day for Uber pickup is",hourlyPickups.idxmax(),"Hours")

"""#### Q.7 Can you create a visualization (e.g., a bar chart or line plot) to represent the number of Uber pickups over time?

**Skill Test:** Data Visualization using Plotting function
"""

import matplotlib.pyplot as plt

# Group by date and count the number of pickups

df["Date"] = df['Date/Time'].dt.date

pickupsCountByDate = df.groupby('Date').size()
# Create a line plot to visualize the number of pickups over time
plt.title('Number of Uber pickups vs time')
pickupsCountByDate.plot(figsize=(10,6))
plt.ylabel('Pickups')

"""#### Q8. Can you create a scatter plot to visualize the distribution of Uber pickups based on latitude and longitude?

**Skill Test:** Scatter Plot
"""

# Create a scatter plot to visualize the distribution of Uber pickups based on latitude and longitude
df.plot.scatter(x='Lat', y='Lon', color='blue', s=10, alpha=0.1, marker='o')
plt.title("Distribution of Uber pickups based on latitude and longitude")
plt.xlabel('Latitude')
plt.ylabel('Longitude')
plt.grid(True)
plt.show()

"""#### Q9. Can you create a bar chart to compare the number of Uber pickups for each TLC base company?

**Skill Test:** Bar Chart
"""

# Create a bar chart to compare the number of Uber pickups for each TLC base company
uniqueBaseCount.plot(kind = 'bar', title = 'Number of Uber pickups for each TLC base company')
plt.xlabel('TLC base company')
plt.ylabel('No. of uber Pickups')

"""#### Q10. Can you create a pie chart to display the percentage distribution of Uber pickups for each day of the week?

**Skill Test:** Pie Chart
"""

# Group by day of the week and count the number of pickups
pickupsByDay = df["Date/Time"].dt.day_name().value_counts()


# Create a pie chart to display the percentage distribution of Uber pickups for each day of the week
plt.pie(x = pickupsByDay.values, labels = pickupsByDay.index,
        autopct  = "%1.1f%%", startangle=90)
plt.title('Percentage distribution of Uber pickups for each day of the week')



